# -*- coding: utf-8 -*-
"""10017---The-Never-Ending-Towers-of-Hanoi------python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QnpF4qZrdAygAjiVIkr5pCaQCCNHvf5r
"""

step = 0

pegs = {
    'A': [],
    'B': [],
    'C': []
}

def printState():
    global step
    if step < 0:
        return

    for p in ['A', 'B', 'C']:
        if pegs[p]:

            disks = ' '.join(str(d) for d in pegs[p])
            print(f"{p}=>   {disks}")
        else:
            print(f"{p}=>")
    print()
    step -= 1

def moveDisk(from_peg, to_peg):
    disk = pegs[from_peg].pop()
    pegs[to_peg].append(disk)
    printState()

def hanoi(n, from_peg, aux_peg, to_peg):
    global step
    if step < 0:
        return

    if n == 1:
        moveDisk(from_peg, to_peg)
        return

    hanoi(n - 1, from_peg, to_peg, aux_peg)
    moveDisk(from_peg, to_peg)
    hanoi(n - 1, aux_peg, from_peg, to_peg)

def main():
    global step, pegs

    case = 0
    while True:
        try:
            n, step = map(int, input().split())
        except:
            break

        if n == 0 and step == 0:
            break

        case += 1
        print(f"Problem #{case}\n")


        pegs = {'A': list(range(n, 0, -1)), 'B': [], 'C': []}

        printState()
        hanoi(n, 'A', 'B', 'C')

if __name__ == "__main__":
    main()